#!/bin/bash
#
# Support functions for ARMX

LOGFILENAME="/host/armx/run/logs/armxdebug.log"
CONSOLELOG="/host/armx/run/logs/qemuconsole.log"

log () {
   if [ "$ARMXLOGFILE" ]
   then
      echo "$*" >> $ARMXLOGFILE
   fi
}

check_if_logging_required () {
   if [ -f /host/armx/run/debug ]
   then
      export ARMXLOGFILE="$LOGFILENAME"
      export CONSOLELOGFILE="$CONSOLELOG"
   fi
}

new_log () {
   if [ -f "$LOGFILENAME" ]
   then
      rm -f "$LOGFILENAME"
      touch "$LOGFILENAME"
   fi

   if [ -f "$CONSOLELOG" ]
   then
      rm -f "$CONSOLELOG"
      touch "$CONSOLELOG"
   fi
}
